### ISSUE TITLE
Create HTML web page for tutorials

### ISSUE THREAD

**Issue by mauleyzaola** [ruleyzaola/tutorial-linux#1]
Move the files we have done so far to HTML and use NodeJs, Grunt, Bower and Bootstrap to automate the process

**Comment by ruleyzaola** [comment]
I dont know how to do that

**Comment by mauleyzaola** [comment]
#source: https://gist.github.com/isaacs/579814
#nodejs setup from git repo compile, make and install slow but more secure


#Nodejs setup Ubuntu server 12.04 from package automatic and fast (needs to be root for npm)

#	Install node.js
#necesario para poder compilar desde codigo fuente archivos de c++ como las dependencias de postgresql
sudo apt-get install software-properties-common python-software-properties python g++ make -y

sudo add-apt-repository ppa:chris-lea/node.js
sudo apt-get update && sudo apt-get install nodejs -y

#dejar npm para que se pueda ejecutar sin necesidad de sudo
mkdir ~/npm
npm config set prefix ~/npm
echo export PATH="$PATH:$HOME/npm/bin" >> ~/.bashrc
echo export NODE_PATH="$NODE_PATH:~/npm/lib/node_modules" >>  ~/.bashrc
source ~/.bashrc

# front-end dependencies recommended to install
npm install --g bower grunt-cli


# opcional
# para actualizar npm a la ultima version
npm install --global npm@latest

**Comment by ruleyzaola** [comment]
thank you it worked
