### ISSUE TITLE
Create page in tutorial - How to implement git security without typing username and password

### ISSUE THREAD

**Issue by mauleyzaola** [ruleyzaola/tutorial-linux#2]
It is boring to input these two values each time we are pushing changes to the repository. Please document in the tutorial the steps required for this task.

**Comment by mauleyzaola** [comment]
Some clues:
1. create a ssh key
2. go to settings in your github account and add the ssh key you just created
3. remove the repository in your local environment and clone again using the ssh link instead of the http
good luck!

**Comment by ruleyzaola** [comment]
ok

On Fri, Jul 17, 2015 at 8:55 AM, Mauricio Leyzaola <notifications@github.com

**Comment by ruleyzaola** [comment]
ssh-keygen
cat ~/.ssh/id_rsa.pub
# register in github the key
