### ISSUE TITLE
Apply HTML tags and CSS Classes using Bootstrap

### ISSUE THREAD

**Issue by mauleyzaola** [ruleyzaola/tutorial-linux#5]
Understand how to change:
1. Color (http://www.w3schools.com/html/html_styles.asp)
2. Background color
3. Font Family (http://www.w3schools.com/html/html_formatting.asp)
4. Font Size

Change classes on HTML elements using Bootstrap
1. The grid system
2. Forms
3. Tables
4. Buttons
Reference: http://getbootstrap.com/

Install another Bootstrap theme and see how to easily change all the look & feel with Bootstrap
Reference: https://github.com/dbtek/bootswatch-dist

**Comment by ruleyzaola** [comment]
professional tool https://color.adobe.com/create/color-wheel/
